version: '3'
services:

  randappdnode0:
    container_name: randappdnode0
    image: "tendermint/randappnode"
    environment:
      - ID=0
      - LOG=${LOG:-randappd.log}
      - HOME=/randappd/node0/randappd
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./build:/randappd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  randappdnode1:
    container_name: randappdnode1
    image: "tendermint/randappnode"
    environment:
      - ID=1
      - LOG=${LOG:-randappd.log}
      - HOME=/randappd/node1/randappd
    ports:
      - "26658-26659:26656-26657"
    volumes:
      - ./build:/randappd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  randappdnode2:
    container_name: randappdnode2
    image: "tendermint/randappnode"
    environment:
      - ID=2
      - LOG=${LOG:-randappd.log}
      - HOME=/randappd/node2/randappd
    ports:
      - "26660-26661:26656-26657"
    volumes:
      - ./build:/randappd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  randappdnode3:
    container_name: randappdnode3
    image: "tendermint/randappnode"
    environment:
      - ID=3
      - LOG=${LOG:-randappd.log}
      - HOME=/randappd/node3/randappd
    ports:
      - "26662-26663:26656-26657"
    volumes:
      - ./build:/randappd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.10.0/16

